[package]
name = "deno-clippy"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_bindgen = "0.6.0"
arboard = "2.1.1"
image = "0.24.3"
serde = { version = "1", features = ["derive"] }
base64 = "0.13.0"
anyhow = "1.0.62"
